services:
  db:
    image: postgres:18-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: apache
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
    - db_data:/var/lib/postgresql

  rustfs:
    image: rustfs/rustfs
    restart: always
    environment:
      - RUSTFS_CONSOLE_ENABLE=true
      - RUSTFS_OBS_LOGGER_LEVEL=info
      - RUSTFS_ACCESS_KEY=apache
      - RUSTFS_SECRET_KEY=airflow
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - storage:/data

volumes:
  db_data:
  storage:
  