version: "3"

services:
  minio:
    image: bitnami/minio
    restart: always
    ports:
    - 9000:9000
    - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=jahodka123
      - MINIO_DEFAULT_BUCKETS=datasets,reports
      - TZ=Europe/Bratislava
    volumes:
    - storage:/bitnami/minio/data

  postgres:
    image: bitnami/postgresql
    volumes:
    - db:/bitnami/postgresql
    ports:
    - 5432:5432
    environment:
      - POSTGRESQL_PASSWORD=secret
      - POSTGRESQL_DATABASE=airflow
      - POSTGRESQL_USERNAME=airflow_user


volumes:
  storage:
  db:
